services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /opt/mysql/data:/var/lib/mysql

  web:
    build: 
      context: ./web
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - '5000:5000'