services:
  web:
    build: 
      context: ./web
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - '5000:5000'
    expose:
      - '5000'
    volumes:
      - ./data/database.db:/db/database.db